
version: 2
jobs:
  ubu1604:
    machine: True
    steps:
      - checkout
      - run: 
          command: ci_scripts/build-image.sh ci_scripts/ubuntu-16_04
      - run: 
          command: ci_scripts/build-package.sh ci_scripts/ubuntu-16_04

  ubu1804:
    machine: True
    steps:
      - checkout
      - run: 
          command: ci_scripts/build-image.sh ci_scripts/ubuntu-18_04
      - run: 
          command: ci_scripts/build-package.sh ci_scripts/ubuntu-18_04


workflows:
  version: 2
  build_all:
    jobs:
      - ubu1604
      - ubu1804
