language: node_js

node_js:
  - 10

os:
  - osx

install:
  - npm install

script:
  - npm run build
  - npm test
  - npm run test-integration

deploy:
  provider: script
  script: npm run dist-ci
  on:
    all_branches: true
  skip_cleanup: true

notifications:
  email: false