blank_issues_enabled: true
contact_links:
  - name: Feature requests
    url: https://support.delta.chat
    about: Please discuss feature requests on our Community forum.
  - name: General Questions
    url: https://support.delta.chat
    about: Please ask general Questions on our Community forum.