# documentation: https://github.com/deltachat/sysadmin/tree/master/download.delta.chat
name: Windows

on: 
  pull_request:
    paths-ignore:
      - 'docs/**'  # only trigger build if a file outside of /docs was changed

jobs:
  upload-preview-linux:
    runs-on: windows-2019
    name: Build & Test (unit + e2e)
    steps:
    - name: Get Pullrequest ID
      id: prepare
      run: |
        set PULLREQUEST_ID=$(echo "${{ github.ref }}" | cut -d '/' -f3)
        echo $GITHUB_EVENT_PATH > github_event_path.txt
        set SHA=$(jq .pull_request.head.sha github_event_path.txt)
        set BASE_URL="https://download.delta.chat/desktop/preview/deltachat-desktop-"

        echo ::set-output name=sha::$SHA
        echo ::set-output name=base-url::$BASE_URL
        echo ::set-output name=prid::$PULLREQUEST_ID
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: change build name and Product Name to development id
      run: |
        node ./bin/github-actions/devbuild.js
    - name: npm install
      run: |
        npm install
    - name: npm build
      run: |
        npm run build
    - name: npm test
      run: |
        npm test
    - name: npm test-integration
      run: |
        npm run test-integration
      env:
        DCC_NEW_TMP_EMAIL: ${{secrets.DCC_NEW_TMP_EMAIL}}
        NODE_ENV: test
