# documentation: https://github.com/deltachat/sysadmin/tree/master/download.delta.chat
name: MacOS

on: 
  pull_request:
    paths-ignore:
      - 'docs/**'  # only trigger build if a file outside of /docs was changed

jobs:
  upload-preview-macos:
    runs-on: macos-latest
    name: Upload Preview
    steps:
    - name: Get Pullrequest ID
      id: prepare
      run: |
        if [ $(expr length "${{ secrets.USERNAME }}") -gt "1" ]; then echo ::set-output name=uploadtoserver::true ;fi
        echo ::set-output name=prid::$(echo "${{ github.ref }}" | cut -d '/' -f3)
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: change build name and Product Name to development id
      run: |
        node ./bin/github-actions/devbuild.js
    - name: npm install, build, test
      run: |
        npm install
        npm run build
    - name: electron builder
      run: npx electron-builder --publish never --mac mas
    - name: renaming
      run: |
        cd dist
        mkdir preview
        ls preview
        cd ..
    - name: compressing mas
      run: zip -r dist/preview/deltachat-desktop-mas-${{ steps.prepare.outputs.prid }}.zip dist/mas
    - name: upload folder
      if: steps.prepare.outputs.uploadtoserver
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        host: "download.delta.chat"
        port: 22
        local: "dist/preview/*"
        remote: "/var/www/html/download/desktop/preview/"
    - name: "Post links to details"
      if: steps.prepare.outputs.uploadtoserver
      run: node ./bin/github-actions/postLinksToDetails.js ${{ steps.prepare.outputs.prid }} ${{ secrets.GITHUB_TOKEN }}
