# documentation: https://github.com/deltachat/sysadmin/tree/master/download.delta.chat
name: Linux

on: 
  pull_request:
    paths-ignore:
      - 'docs/**'  # only trigger build if a file outside of /docs was changed

jobs:
  upload-preview-linux:
    runs-on: ubuntu-18.04
    name: Upload Preview
    steps:
    - name: Get Pullrequest ID
      id: prepare
      run: |
        echo ::set-output name=prid::$(echo "${{ github.ref }}" | cut -d '/' -f3)
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: change build name and Product Name to development id
      run: |
        node ./bin/github-actions/devbuild.js
    - name: npm install, build, test
      run: |
        npm install
        npm run build
    - name: electron builder
      run: npx electron-builder --publish never --linux
    - name: renaming
      run: |
        cd dist
        mkdir preview
        mv *.AppImage preview/deltachat-desktop-${{ steps.prepare.outputs.prid }}.AppImage
        ls preview
        cd ..
    - name: upload folder
      if: ${{ secrets.USERNAME }} # if secret is there upload to server
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        host: "download.delta.chat"
        port: 22
        local: "dist/preview/*"
        remote: "/var/www/html/download/desktop/preview/"
    - name: "Post links to details"
      if: ${{ secrets.USERNAME }} # if secret is there upload to server
      run: node ./bin/github-actions/postLinksToDetails.js ${{ steps.prepare.outputs.prid }} ${{ secrets.GITHUB_TOKEN }}
    - name: "zip result"
      if: ${{ !secrets.USERNAME }} # if secret is not there upload to artifact
      run: zip -r dist/preview.zip dist/preview/
    - name: Upload result to artifacts
      if: ${{ !secrets.USERNAME }} # if secret is not there upload to artifact
      uses: actions/upload-artifact@master
      with:
        name: Files
        path: dist/preview.zip
