name: Preview

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install, build, test
      run: |
        npm install
        npm run build
        npm test
    - name: electron builder
      run: npx electron-builder --linux --win --mac
    - uses: actions/upload-artifact@master
      with:
        name: Linux Appimage
        path: dist/*.Appimage
    - uses: actions/upload-artifact@master
      with:
        name: Linux deb
        path: dist/*.deb
    - uses: actions/upload-artifact@master
      with:
        name: Windows Zip
        path: dist/win-unpacked
    - uses: actions/upload-artifact@master
      with:
        name: Mac dmg
        path: dist/*dmg
