name: test-e2e-ci

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and build
      run: |
        npm ci
        npm run build
      env:
        CI: true
    - uses: DevExpress/testcafe-action@latest
      with:
        version: "1.6.0"
        args: "--skip-js-errors \"electron:./\" \"./test/testcafe/test_ci.js\""
      env:
        DCC_NEW_TMP_EMAIL: ${{secrets.DCC_NEW_TMP_EMAIL}}
        NODE_ENV: test